### ISSUE TITLE
Compilation Error in a base rock installation

### ISSUE THREAD

**Issue by jhidalgocarrio** [envire/slam-maps#9]
This package does not compile in a base rock installation. It search for PrimitivesFactory from osgviz but slam/maps does not depends on osgviz (not listed in the manifest)

@arneboe What is the current status for the vizkit3d and osgviz integration

**Comment by arneboe** [comment]
Does it compile if you add the dependency in the manifest? 
The visualizers are using some osgviz primitves.

**Comment by jhidalgocarrio** [comment]
I guess so but... why is it not in the manifest? How is the current status of vizkit3d and osgviz integration.
Could you please specify the package dependencies, that I can add them in envire-package_set? Currently I can only see an internal gitlab osgviz-package_set.

**Comment by annaborn** [comment]
osgviz and vizkit3d integration has been done already. 
No particular reason why the dependency is missing in the manifest. Just someone has forgotten to put it there. :)
Please check out the last commits. 85326b75c0916ceee59c75cd7992f948e651f12e
It should add the missing dependency to osgviz in the maps manifest.

In the envire-package_set you should put: 

name: envire

imports:
    - github: rock-simulation/package_set
    - github: rock-gui/osgviz-package_set

Please write back if it could solve your problem.

Edit: change the name of osgviz-package_set!!!

**Comment by jhidalgocarrio** [comment]
> Please write back if it could solve your problem.

I needed to adapt the cmake to not compile the test/viz when osgviz is not present. Have a look at: https://github.com/envire/slam-maps/commit/08f416ce09be29f3315a9b9026a149c334eaec5f 

Also not very sure how autorproj handles the optional="1". For example, even when gui/vizkit3d is not installed and it's optional='1', autoproj checkout the gui/vizkit3d package anyway. Any comment on that?

**Comment by annaborn** [comment]
To your question: "optional" works by the definition in the package sets. 
Eg. if there is no any definition of gui/vizkit3d in the package sets, it will not be installed. However, if the autoproj finds the requested definition, it will download the package.
Since we use rock-core/rock-package_set, the package "gui/vizkit3d" is defined.

Your commit is fine. 
Instead of "pkg_check_modules" you can use Rock macro "rock_find_pkgconfig"
rock_find_pkgconfig(PrimitivesFactory)
In this case PrimitivesFactory_FOUND

**Comment by jhidalgocarrio** [comment]
@annaborn  thanks
